In [31]:
import requests
import pandas as pd
from requests.auth import HTTPBasicAuth
import string
import time
from datetime import datetime


USERNAME = "gabriel.bezhi@stud.hslu.ch"
PASSWORD = "uBFh6fsx"
BASE_URL = "https://www.zefix.admin.ch/ZefixPublicREST"

auth = HTTPBasicAuth(USERNAME, PASSWORD)
headers = {"Accept": "application/json", "Content-Type": "application/json"}

In [40]:

import time
import requests
import pandas as pd

# BASE_URL, auth, headers werden als bereits definiert angenommen
CANTON = "LU"
SLEEP_BETWEEN = 0.3

# 1-stellige Präfixe: a-z + 0-9 = 36 Kombinationen
prefixes = list(string.ascii_lowercase + string.digits)

all_hits = []

for i, prefix in enumerate(prefixes, 1):
    payload = {
        "name": f"{prefix}*",
        "canton": CANTON,
        "activeOnly": True,
    }

    try:
        resp = requests.post(
            f"{BASE_URL}/api/v1/company/search",
            auth=auth, headers=headers, json=payload, timeout=30,
        )
        resp.raise_for_status()
        search_results = resp.json()
        hits = search_results if isinstance(search_results, list) else search_results.get("list", [])
    except Exception as e:
        print(f"[{i}/{len(prefixes)}] {prefix}*: FEHLER {e}")
        continue

    if hits:
        all_hits.extend(hits)
        print(f"[{i}/{len(prefixes)}] {prefix}*: +{len(hits)} (total: {len(all_hits)})")
    else:
        print(f"[{i}/{len(prefixes)}] {prefix}*: 0 Treffer")

    time.sleep(SLEEP_BETWEEN)

# In DataFrame packen und über uid deduplizieren
df_search = pd.json_normalize(all_hits)
if "uid" in df_search.columns:
    before = len(df_search)
    df_search = df_search.drop_duplicates(subset="uid", keep="first").reset_index(drop=True)
    print(f"\nDedup: {before} → {len(df_search)} unique Firmen")

print(f"Fertig: {len(df_search)} unique Firmen in Kanton {CANTON}")
df_search

[1/36] a*: +2904 (total: 2904)
[2/36] b*: +2686 (total: 5590)
[3/36] c*: +1682 (total: 7272)
[4/36] d*: +1381 (total: 8653)
[5/36] e*: +1386 (total: 10039)
[6/36] f*: +1528 (total: 11567)
[7/36] g*: +1665 (total: 13232)
[8/36] h*: +1707 (total: 14939)
[9/36] i*: +1119 (total: 16058)
[10/36] j*: +564 (total: 16622)
[11/36] k*: +1444 (total: 18066)
[12/36] l*: +1370 (total: 19436)
[13/36] m*: +2584 (total: 22020)
[14/36] n*: +819 (total: 22839)
[15/36] o*: +546 (total: 23385)
[16/36] p*: +1958 (total: 25343)
[17/36] q*: +93 (total: 25436)
[18/36] r*: +1651 (total: 27087)
[19/36] s*: +3932 (total: 31019)
[20/36] t*: +1412 (total: 32431)
[21/36] u*: +270 (total: 32701)
[22/36] v*: +752 (total: 33453)
[23/36] w*: +1177 (total: 34630)
[24/36] x*: +67 (total: 34697)
[25/36] y*: +106 (total: 34803)
[26/36] z*: +437 (total: 35240)
[27/36] 0*: +3 (total: 35243)
[28/36] 1*: +35 (total: 35278)
[29/36] 2*: +30 (total: 35308)
[30/36] 3*: +34 (total: 35342)
[31/36] 4*: +40 (total: 35382)
[32/36] 5*: +9 (total: 35391)
[33/36] 6*: +3 (total: 35394)
[34/36] 7*: +10 (total: 35404)
[35/36] 8*: +4 (total: 35408)
[36/36] 9*: +4 (total: 35412)

Dedup: 35412 → 35340 unique Firmen
Fertig: 35340 unique Firmen in Kanton LU

,name,ehraid,uid,chid,legalSeatId,legalSeat,registryOfCommerceId,status,sogcDate,deletionDate,legalForm.id,legalForm.uid,legalForm.name.de,legalForm.name.fr,legalForm.name.it,legalForm.name.en,legalForm.shortName.de,legalForm.shortName.fr,legalForm.shortName.it,legalForm.shortName.en
0,A1 AUTO AG in Liquidation,437580,CHE107251578,CH10030216915,1094,Nottwil,100,BEING_CANCELLED,2026-03-24,None,3,0106,Aktiengesellschaft,Société anonyme,Società anonima,Corporation,AG,SA,SA,Ltd
1,A1 Automobile GmbH,1434117,CHE338108860,CH10048096209,1093,Neuenkirch,100,ACTIVE,2020-04-27,None,4,0107,Gesellschaft mit beschränkter Haftung,Société à responsabilité limitée,Società a garanzia limitata,Limited Liability Company,GmbH,Sàrl,Sagl,LLC
2,A1 engineering ag,1055874,CHE212607256,CH10037944356,1084,Eich,100,ACTIVE,2022-11-01,None,3,0106,Aktiengesellschaft,Société anonyme,Società anonima,Corporation,AG,SA,SA,Ltd
3,A1 Immobilien & Consulting GmbH,1286247,CHE291691203,CH10048029571,1098,Ruswil,100,ACTIVE,2022-07-13,None,4,0107,Gesellschaft mit beschränkter Haftung,Société à responsabilité limitée,Società a garanzia limitata,Limited Liability Company,GmbH,Sàrl,Sagl,LLC
4,A1-Service & Wellness Markus Bünder,1522916,CHE256528001,CH10018136673,1098,Ruswil,100,ACTIVE,2022-02-09,None,1,0101,Einzelunternehmen,Entreprise individuelle,Ditta individuale,Sole proprietorship,EIU,EI,IPI,SP
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35335,8tungnaomi GmbH in Liquidation,1484627,CHE475219866,CH02040738992,1086,Grosswangen,100,BEING_CANCELLED,2025-05-30,None,4,0107,Gesellschaft mit beschränkter Haftung,Société à responsabilité limitée,Società a garanzia limitata,Limited Liability Company,GmbH,Sàrl,Sagl,LLC
35336,95' - Holding AG,1555017,CHE203663296,CH40034517342,1103,Sursee,100,ACTIVE,2025-03-05,None,3,0106,Aktiengesellschaft,Société anonyme,Società anonima,Corporation,AG,SA,SA,Ltd
35337,969.coffee AG,1308378,CHE313609927,CH10038039590,1024,Emmen,100,ACTIVE,2026-01-15,None,3,0106,Aktiengesellschaft,Société anonyme,Società anonima,Corporation,AG,SA,SA,Ltd
35338,9.81 Arbeitssicherheit AG,1004437,CHE380242043,CH10037922823,1024,Emmen,100,ACTIVE,2026-02-06,None,3,0106,Aktiengesellschaft,Société anonyme,Società anonima,Corporation,AG,SA,SA,Ltd
35339,9K Consulting GmbH,1359322,CHE137269301,CH10048062369,1086,Grosswangen,100,ACTIVE,2018-09-06,None,4,0107,Gesellschaft mit beschränkter Haftung,Société à responsabilité limitée,Società a garanzia limitata,Limited Liability Company,GmbH,Sàrl,Sagl,LLC

In [41]:
def fetch_details(uid: str) -> list[dict]:
    """Holt alle Detail-Einträge zu einer UID. Gibt leere Liste bei Fehler zurück."""
    try:
        r = requests.get(
            f"{BASE_URL}/api/v1/company/uid/{uid}",
            auth=auth, headers={"Accept": "application/json"}, timeout=30,
        )
        r.raise_for_status()
        data = r.json()
        return data if isinstance(data, list) else [data]
    except requests.HTTPError as e:
        print(f"  ! Fehler bei UID {uid}: {e}")
        return []

In [ ]:
all_details = []
for uid in df_search["uid"].dropna().unique():
    print(f"Lade Details für {uid} ...")
    all_details.extend(fetch_details(uid))
    time.sleep(0.2)

df_details = pd.json_normalize(all_details, sep=".")

Lade Details für CHE107251578 ...
Lade Details für CHE338108860 ...
Lade Details für CHE212607256 ...
Lade Details für CHE291691203 ...
Lade Details für CHE256528001 ...
Lade Details für CHE144486401 ...
Lade Details für CHE379851330 ...
Lade Details für CHE334250418 ...
Lade Details für CHE115464225 ...
Lade Details für CHE134913146 ...
Lade Details für CHE175035678 ...
Lade Details für CHE137692125 ...
Lade Details für CHE112841840 ...
Lade Details für CHE104802192 ...
Lade Details für CHE287228842 ...
Lade Details für CHE112157206 ...
Lade Details für CHE303920217 ...
Lade Details für CHE110498317 ...
Lade Details für CHE106835972 ...
Lade Details für CHE495219898 ...
Lade Details für CHE341446292 ...
Lade Details für CHE105310968 ...
Lade Details für CHE106699479 ...
Lade Details für CHE466314595 ...
Lade Details für CHE316021073 ...
Lade Details für CHE108531017 ...
Lade Details für CHE392282368 ...
Lade Details für CHE441768158 ...
Lade Details für CHE439676305 ...
Lade Details für CHE108451849 ...
Lade Details für CHE331892170 ...
Lade Details für CHE308963694 ...
Lade Details für CHE134719986 ...
Lade Details für CHE282906563 ...
Lade Details für CHE433261236 ...
Lade Details für CHE381250654 ...
Lade Details für CHE398846358 ...
Lade Details für CHE113552686 ...
Lade Details für CHE112109383 ...
Lade Details für CHE131940106 ...
Lade Details für CHE231896747 ...
Lade Details für CHE339986047 ...
Lade Details für CHE101866310 ...
Lade Details für CHE445271603 ...
Lade Details für CHE211254959 ...
Lade Details für CHE462865896 ...
Lade Details für CHE101926797 ...
Lade Details für CHE399121660 ...
Lade Details für CHE377635844 ...
Lade Details für CHE220040802 ...
Lade Details für CHE476892994 ...
Lade Details für CHE212920500 ...
Lade Details für CHE107323516 ...
Lade Details für CHE214284342 ...
Lade Details für CHE432582181 ...
Lade Details für CHE114849002 ...
Lade Details für CHE101793740 ...
Lade Details für CHE241440047 ...
Lade Details für CHE328501581 ...
Lade Details für CHE269224409 ...
Lade Details für CHE161976681 ...
Lade Details für CHE430460213 ...
Lade Details für CHE189032611 ...
Lade Details für CHE439413705 ...
Lade Details für CHE108775944 ...
Lade Details für CHE103553684 ...
Lade Details für CHE476009283 ...
Lade Details für CHE114786436 ...
Lade Details für CHE379098466 ...
Lade Details für CHE106781224 ...
Lade Details für CHE105432092 ...
Lade Details für CHE105499630 ...
Lade Details für CHE106551658 ...
Lade Details für CHE282016043 ...
Lade Details für CHE298965991 ...
Lade Details für CHE272729503 ...
Lade Details für CHE395877569 ...
Lade Details für CHE156580811 ...
Lade Details für CHE102430151 ...
Lade Details für CHE442146976 ...
Lade Details für CHE102013729 ...
Lade Details für CHE495193804 ...
Lade Details für CHE270762671 ...
Lade Details für CHE107227522 ...
Lade Details für CHE115877082 ...
Lade Details für CHE286429579 ...
Lade Details für CHE107870497 ...
Lade Details für CHE163778318 ...
Lade Details für CHE248650060 ...
Lade Details für CHE106925919 ...
Lade Details für CHE330876702 ...
Lade Details für CHE139132825 ...
Lade Details für CHE398769692 ...
Lade Details für CHE100351670 ...
Lade Details für CHE433164745 ...
Lade Details für CHE471046934 ...
Lade Details für CHE115327611 ...
Lade Details für CHE344679964 ...
Lade Details für CHE113011999 ...
Lade Details für CHE430987696 ...
Lade Details für CHE103955887 ...
Lade Details für CHE463811130 ...
Lade Details für CHE107272988 ...
Lade Details für CHE332785795 ...
Lade Details für CHE416550567 ...
Lade Details für CHE145124308 ...
Lade Details für CHE319270603 ...
Lade Details für CHE181299398 ...
Lade Details für CHE276898926 ...
Lade Details für CHE425633620 ...
Lade Details für CHE425057254 ...
Lade Details für CHE110122289 ...
Lade Details für CHE434299862 ...
Lade Details für CHE428782328 ...
Lade Details für CHE428123396 ...
Lade Details für CHE166695315 ...
Lade Details für CHE392719862 ...
Lade Details für CHE241404241 ...
Lade Details für CHE210188047 ...
Lade Details für CHE195357783 ...
Lade Details für CHE110206911 ...
Lade Details für CHE457984118 ...
Lade Details für CHE460172635 ...
Lade Details für CHE309279749 ...
Lade Details für CHE115000280 ...
Lade Details für CHE288185543 ...
Lade Details für CHE315173964 ...
Lade Details für CHE116087326 ...
Lade Details für CHE239475579 ...
Lade Details für CHE132375189 ...
Lade Details für CHE168655249 ...
Lade Details für CHE152555369 ...
Lade Details für CHE257219347 ...
Lade Details für CHE480455036 ...
Lade Details für CHE113083757 ...
Lade Details für CHE289592856 ...
Lade Details für CHE137178302 ...
Lade Details für CHE114490639 ...
Lade Details für CHE110263501 ...
Lade Details für CHE379060831 ...
Lade Details für CHE106248303 ...
Lade Details für CHE107608344 ...
Lade Details für CHE101013394 ...
Lade Details für CHE108420820 ...
Lade Details für CHE443648246 ...
Lade Details für CHE249032077 ...
Lade Details für CHE156064018 ...
Lade Details für CHE116057130 ...
Lade Details für CHE113271460 ...
Lade Details für CHE463251142 ...
Lade Details für CHE131074992 ...
Lade Details für CHE371759531 ...
Lade Details für CHE103802901 ...
Lade Details für CHE113993263 ...
Lade Details für CHE485022816 ...
Lade Details für CHE110350560 ...
Lade Details für CHE446683517 ...
Lade Details für CHE439828058 ...
Lade Details für CHE104286793 ...
Lade Details für CHE110347776 ...
Lade Details für CHE216852406 ...
Lade Details für CHE105480122 ...
Lade Details für CHE198437496 ...
Lade Details für CHE113999231 ...
Lade Details für CHE453789693 ...
Lade Details für CHE222199046 ...
Lade Details für CHE238953582 ...
Lade Details für CHE407081243 ...
Lade Details für CHE390113602 ...
Lade Details für CHE224189159 ...
Lade Details für CHE319033345 ...
Lade Details für CHE401706530 ...
Lade Details für CHE103255117 ...
Lade Details für CHE283006716 ...
Lade Details für CHE308573927 ...
Lade Details für CHE314370930 ...
Lade Details für CHE199493557 ...
Lade Details für CHE279316852 ...
Lade Details für CHE240145640 ...
Lade Details für CHE101122646 ...
Lade Details für CHE115264672 ...
Lade Details für CHE464902516 ...
Lade Details für CHE382062664 ...
Lade Details für CHE111993714 ...
Lade Details für CHE186051888 ...
Lade Details für CHE476672263 ...
Lade Details für CHE115058931 ...
Lade Details für CHE109567265 ...
Lade Details für CHE173761609 ...
Lade Details für CHE366706670 ...
Lade Details für CHE113826145 ...
Lade Details für CHE466686743 ...
Lade Details für CHE100145550 ...
Lade Details für CHE228383306 ...
Lade Details für CHE499046088 ...
Lade Details für CHE387955552 ...
Lade Details für CHE112719392 ...
Lade Details für CHE386945054 ...
Lade Details für CHE290225005 ...
Lade Details für CHE105694060 ...
Lade Details für CHE113990951 ...
Lade Details für CHE388088521 ...
Lade Details für CHE250771313 ...
Lade Details für CHE297118741 ...
Lade Details für CHE300299378 ...
Lade Details für CHE486281740 ...
Lade Details für CHE107227580 ...
Lade Details für CHE487492512 ...
Lade Details für CHE109693898 ...
Lade Details für CHE372451277 ...
Lade Details für CHE115692683 ...
Lade Details für CHE291303607 ...
Lade Details für CHE441740409 ...
Lade Details für CHE134703672 ...
Lade Details für CHE417892266 ...
Lade Details für CHE114279228 ...
Lade Details für CHE278872866 ...
Lade Details für CHE359794373 ...
Lade Details für CHE360494593 ...
Lade Details für CHE115901929 ...
Lade Details für CHE219223230 ...
Lade Details für CHE159162686 ...
Lade Details für CHE275019467 ...
Lade Details für CHE188085556 ...
Lade Details für CHE311422878 ...
Lade Details für CHE100850878 ...
Lade Details für CHE433951743 ...
Lade Details für CHE332195613 ...
Lade Details für CHE394872210 ...
Lade Details für CHE226846040 ...
Lade Details für CHE109099436 ...
Lade Details für CHE408417564 ...
Lade Details für CHE349742972 ...
Lade Details für CHE112005453 ...
Lade Details für CHE444722655 ...
Lade Details für CHE342053328 ...
Lade Details für CHE412095498 ...
Lade Details für CHE216720851 ...
Lade Details für CHE137706916 ...
Lade Details für CHE106179524 ...
Lade Details für CHE113786729 ...
Lade Details für CHE198280585 ...
Lade Details für CHE273701677 ...
Lade Details für CHE464553189 ...
Lade Details für CHE328855406 ...
Lade Details für CHE364286941 ...
Lade Details für CHE101020419 ...
Lade Details für CHE359672942 ...
Lade Details für CHE214498713 ...
Lade Details für CHE109597912 ...
Lade Details für CHE451586446 ...
Lade Details für CHE186779062 ...
Lade Details für CHE115468714 ...
Lade Details für CHE261546944 ...
Lade Details für CHE264229641 ...
Lade Details für CHE114940789 ...
Lade Details für CHE105112859 ...
Lade Details für CHE304433204 ...
Lade Details für CHE459516923 ...
Lade Details für CHE433089836 ...
Lade Details für CHE115150904 ...
Lade Details für CHE114263227 ...
Lade Details für CHE358269963 ...
Lade Details für CHE240649136 ...
Lade Details für CHE461323279 ...
Lade Details für CHE259030418 ...
Lade Details für CHE172046059 ...
Lade Details für CHE134161400 ...
Lade Details für CHE107524902 ...
Lade Details für CHE152830311 ...
Lade Details für CHE114083257 ...
Lade Details für CHE323931997 ...
Lade Details für CHE265406584 ...
Lade Details für CHE207888463 ...
Lade Details für CHE483316572 ...
Lade Details für CHE430467043 ...
Lade Details für CHE445995204 ...
Lade Details für CHE186147554 ...
Lade Details für CHE145080800 ...
Lade Details für CHE377557842 ...
Lade Details für CHE102185388 ...
Lade Details für CHE420919983 ...
Lade Details für CHE110617740 ...
Lade Details für CHE272919995 ...
Lade Details für CHE479859527 ...
Lade Details für CHE362711703 ...
Lade Details für CHE156013268 ...
Lade Details für CHE156605753 ...
Lade Details für CHE385688021 ...
Lade Details für CHE105786644 ...
Lade Details für CHE253872011 ...
Lade Details für CHE280466116 ...
Lade Details für CHE438665813 ...
Lade Details für CHE231756603 ...
Lade Details für CHE421277696 ...
Lade Details für CHE143488610 ...
Lade Details für CHE165790709 ...
Lade Details für CHE303938039 ...
Lade Details für CHE443976058 ...
Lade Details für CHE303985814 ...
Lade Details für CHE430272031 ...
Lade Details für CHE496995338 ...
Lade Details für CHE325296479 ...
Lade Details für CHE114924477 ...
Lade Details für CHE244219473 ...
Lade Details für CHE432097098 ...
Lade Details für CHE489855577 ...
Lade Details für CHE112023669 ...
Lade Details für CHE115012691 ...
Lade Details für CHE112019337 ...
Lade Details für CHE102360349 ...
Lade Details für CHE135475166 ...
Lade Details für CHE107398885 ...
Lade Details für CHE292153055 ...
Lade Details für CHE113305337 ...
Lade Details für CHE103784634 ...
Lade Details für CHE100985194 ...
Lade Details für CHE205185445 ...
Lade Details für CHE109377492 ...
Lade Details für CHE218434882 ...
Lade Details für CHE334786624 ...
Lade Details für CHE456307056 ...
Lade Details für CHE480253254 ...
Lade Details für CHE260886283 ...
Lade Details für CHE107275627 ...
Lade Details für CHE105330511 ...
Lade Details für CHE105918271 ...
Lade Details für CHE110379960 ...
Lade Details für CHE462835524 ...
Lade Details für CHE380071698 ...
Lade Details für CHE382757097 ...
Lade Details für CHE112231110 ...
Lade Details für CHE113962676 ...
Lade Details für CHE110125394 ...
Lade Details für CHE498249016 ...
Lade Details für CHE266262572 ...
Lade Details für CHE209324266 ...
Lade Details für CHE415726349 ...
Lade Details für CHE227063164 ...
Lade Details für CHE438845686 ...
Lade Details für CHE144157009 ...
Lade Details für CHE173869773 ...
Lade Details für CHE309691222 ...
Lade Details für CHE183515437 ...
Lade Details für CHE460034275 ...
Lade Details für CHE161867483 ...
Lade Details für CHE377611418 ...
Lade Details für CHE106625386 ...
Lade Details für CHE491329275 ...
Lade Details für CHE150873404 ...
Lade Details für CHE415446134 ...
Lade Details für CHE471196114 ...
Lade Details für CHE462963116 ...
Lade Details für CHE231910620 ...
Lade Details für CHE386394450 ...
Lade Details für CHE330301637 ...
Lade Details für CHE399384596 ...
Lade Details für CHE439890910 ...
Lade Details für CHE113897257 ...
Lade Details für CHE108104879 ...
Lade Details für CHE383284931 ...
Lade Details für CHE248441705 ...
Lade Details für CHE115742453 ...
Lade Details für CHE196933235 ...
Lade Details für CHE278667303 ...
Lade Details für CHE109264994 ...
Lade Details für CHE465110529 ...
Lade Details für CHE264377224 ...
Lade Details für CHE102865833 ...
Lade Details für CHE107276526 ...
Lade Details für CHE327445796 ...
Lade Details für CHE171185238 ...
Lade Details für CHE141881994 ...
Lade Details für CHE278166745 ...
Lade Details für CHE286375883 ...
Lade Details für CHE146734610 ...
Lade Details für CHE301736016 ...
Lade Details für CHE160560792 ...
Lade Details für CHE436769821 ...
Lade Details für CHE313594533 ...
Lade Details für CHE114313090 ...
Lade Details für CHE281178542 ...
Lade Details für CHE346208593 ...
Lade Details für CHE103203356 ...
Lade Details für CHE281615933 ...
Lade Details für CHE219708970 ...
Lade Details für CHE417632995 ...
Lade Details für CHE285421782 ...
Lade Details für CHE288090612 ...
Lade Details für CHE187748845 ...
Lade Details für CHE297264153 ...
Lade Details für CHE417514692 ...
Lade Details für CHE266953937 ...
Lade Details für CHE221672560 ...
Lade Details für CHE457835369 ...
Lade Details für CHE112335152 ...
Lade Details für CHE243814288 ...
Lade Details für CHE116361088 ...
Lade Details für CHE105421071 ...
Lade Details für CHE105912742 ...
Lade Details für CHE259047637 ...
Lade Details für CHE115692708 ...
Lade Details für CHE328166525 ...
Lade Details für CHE281607537 ...
Lade Details für CHE109966116 ...
Lade Details für CHE107155147 ...
Lade Details für CHE112506755 ...
Lade Details für CHE335780972 ...
Lade Details für CHE453046818 ...
Lade Details für CHE103418833 ...
Lade Details für CHE389457779 ...
Lade Details für CHE356849641 ...
Lade Details für CHE198138208 ...
Lade Details für CHE417994872 ...
Lade Details für CHE106527967 ...
Lade Details für CHE441793104 ...
Lade Details für CHE414608109 ...
Lade Details für CHE107866981 ...
Lade Details für CHE110611944 ...
Lade Details für CHE285066735 ...
Lade Details für CHE464873435 ...
Lade Details für CHE372932140 ...
Lade Details für CHE107240250 ...
Lade Details für CHE105802496 ...
Lade Details für CHE338030956 ...
Lade Details für CHE383703537 ...
Lade Details für CHE112478917 ...
Lade Details für CHE287849694 ...
Lade Details für CHE298382855 ...
Lade Details für CHE275027834 ...
Lade Details für CHE109098023 ...
Lade Details für CHE105918615 ...
Lade Details für CHE115612276 ...
Lade Details für CHE108617570 ...
Lade Details für CHE114280668 ...
Lade Details für CHE113559004 ...
Lade Details für CHE184169444 ...
Lade Details für CHE197685465 ...
Lade Details für CHE102733976 ...
Lade Details für CHE467532806 ...
Lade Details für CHE214625696 ...
Lade Details für CHE297262208 ...
Lade Details für CHE101560207 ...
Lade Details für CHE116299153 ...
Lade Details für CHE394742990 ...
Lade Details für CHE290288253 ...
Lade Details für CHE341950320 ...
Lade Details für CHE217208739 ...
Lade Details für CHE267464546 ...
Lade Details für CHE107981613 ...
Lade Details für CHE105954752 ...
Lade Details für CHE223472635 ...
Lade Details für CHE310139351 ...
Lade Details für CHE276686643 ...
Lade Details für CHE154164695 ...
Lade Details für CHE479776278 ...
Lade Details für CHE484603519 ...
Lade Details für CHE414006548 ...
Lade Details für CHE102420715 ...
Lade Details für CHE331555235 ...
Lade Details für CHE201083656 ...
Lade Details für CHE160756533 ...
Lade Details für CHE109098069 ...
Lade Details für CHE103183854 ...
Lade Details für CHE107314150 ...
Lade Details für CHE116076908 ...
Lade Details für CHE101192204 ...
Lade Details für CHE105139143 ...
Lade Details für CHE246260073 ...
Lade Details für CHE112675843 ...
Lade Details für CHE102626412 ...
Lade Details für CHE296814855 ...
Lade Details für CHE439478136 ...
Lade Details für CHE233713929 ...
Lade Details für CHE474380430 ...
Lade Details für CHE204644077 ...
Lade Details für CHE226399236 ...
Lade Details für CHE475201085 ...
Lade Details für CHE405981093 ...
Lade Details für CHE477300657 ...
Lade Details für CHE105850779 ...
Lade Details für CHE182859503 ...
Lade Details für CHE493013506 ...
Lade Details für CHE324060721 ...
Lade Details für CHE108167124 ...
Lade Details für CHE419523963 ...
Lade Details für CHE405574552 ...
Lade Details für CHE485379543 ...
Lade Details für CHE109097992 ...
Lade Details für CHE442447099 ...
Lade Details für CHE430610470 ...
Lade Details für CHE102964429 ...
Lade Details für CHE328750523 ...
Lade Details für CHE116173440 ...
Lade Details für CHE358405806 ...
Lade Details für CHE248448305 ...
Lade Details für CHE111792245 ...
Lade Details für CHE301689055 ...
Lade Details für CHE225738241 ...
Lade Details für CHE114350783 ...
Lade Details für CHE235412686 ...
Lade Details für CHE138456490 ...
Lade Details für CHE426973171 ...
Lade Details für CHE397527933 ...
Lade Details für CHE312376258 ...
Lade Details für CHE182126731 ...
Lade Details für CHE390829681 ...
Lade Details für CHE247483150 ...
Lade Details für CHE265303079 ...
Lade Details für CHE309471347 ...
Lade Details für CHE408874648 ...
Lade Details für CHE106846792 ...
Lade Details für CHE252990398 ...
Lade Details für CHE413816496 ...
Lade Details für CHE274316773 ...
Lade Details für CHE392387116 ...
Lade Details für CHE183354140 ...
Lade Details für CHE110288441 ...
Lade Details für CHE183465822 ...
Lade Details für CHE115200778 ...
Lade Details für CHE130578221 ...
Lade Details für CHE241824488 ...
Lade Details für CHE107249096 ...
Lade Details für CHE454475760 ...
Lade Details für CHE394833345 ...
Lade Details für CHE105094204 ...
Lade Details für CHE114143824 ...
Lade Details für CHE100736596 ...
Lade Details für CHE387521633 ...
Lade Details für CHE108404927 ...
Lade Details für CHE101405802 ...
Lade Details für CHE286709116 ...
Lade Details für CHE339689419 ...
Lade Details für CHE330640944 ...
Lade Details für CHE279529069 ...
Lade Details für CHE103814005 ...
Lade Details für CHE190655150 ...
Lade Details für CHE114353149 ...
Lade Details für CHE107866567 ...
Lade Details für CHE488172748 ...
Lade Details für CHE267384982 ...
Lade Details für CHE214555268 ...
Lade Details für CHE110686971 ...
Lade Details für CHE345697433 ...
Lade Details für CHE116210667 ...
Lade Details für CHE439789783 ...
Lade Details für CHE200233723 ...
Lade Details für CHE408523924 ...
Lade Details für CHE112249593 ...
Lade Details für CHE169262912 ...
Lade Details für CHE366691376 ...
Lade Details für CHE115753563 ...
Lade Details für CHE105104311 ...
Lade Details für CHE254203611 ...
Lade Details für CHE320913342 ...
Lade Details für CHE104764574 ...
Lade Details für CHE466418763 ...
Lade Details für CHE164658786 ...
Lade Details für CHE107295297 ...
Lade Details für CHE107969055 ...
Lade Details für CHE310647883 ...
Lade Details für CHE322496651 ...
Lade Details für CHE108452228 ...
Lade Details für CHE384540031 ...
Lade Details für CHE109923236 ...
Lade Details für CHE106766696 ...
Lade Details für CHE396189265 ...
Lade Details für CHE322637503 ...
Lade Details für CHE104697707 ...
Lade Details für CHE110230016 ...
Lade Details für CHE116218930 ...
Lade Details für CHE112506761 ...
Lade Details für CHE234158522 ...
Lade Details für CHE288702303 ...
Lade Details für CHE486178697 ...
Lade Details für CHE107912374 ...
Lade Details für CHE359405482 ...
Lade Details für CHE106413996 ...
Lade Details für CHE103472206 ...
Lade Details für CHE105958069 ...
Lade Details für CHE227073323 ...
Lade Details für CHE146086633 ...
Lade Details für CHE393830002 ...
Lade Details für CHE411938668 ...
Lade Details für CHE376131883 ...
Lade Details für CHE295782371 ...
Lade Details für CHE370890708 ...
Lade Details für CHE478399032 ...

In [44]:
df_merged = df_search.merge(df_details, on="uid", how="left", suffixes=("_search", "_detail"))

print(f"\nSuche: {len(df_search)} Treffer")
print(f"Details: {len(df_details)} Einträge")
print(f"Merged: {len(df_merged)} Zeilen")

df_merged.head(n=10)

Suche: 35340 Treffer
Details: 35340 Einträge
Merged: 35340 Zeilen

,name_search,ehraid_search,uid,chid_search,legalSeatId_search,legalSeat_search,registryOfCommerceId_search,status_search,sogcDate_search,deletionDate_search,...,address.street,address.houseNumber,address.addon,address.poBox,address.city,address.swissZipCode,zefixDetailWeb.de,zefixDetailWeb.fr,zefixDetailWeb.it,zefixDetailWeb.en
0,A1 AUTO AG in Liquidation,437580,CHE107251578,CH10030216915,1094,Nottwil,100,BEING_CANCELLED,2026-03-24,None,...,Kantonsstrasse,20,,,Nottwil,6207,https://www.zefix.admin.ch/de/search/entity/li...,https://www.zefix.admin.ch/fr/search/entity/li...,https://www.zefix.admin.ch/it/search/entity/li...,https://www.zefix.admin.ch/en/search/entity/li...
1,A1 Automobile GmbH,1434117,CHE338108860,CH10048096209,1093,Neuenkirch,100,ACTIVE,2020-04-27,None,...,Surseestrasse,14,,,Neuenkirch,6206,https://www.zefix.admin.ch/de/search/entity/li...,https://www.zefix.admin.ch/fr/search/entity/li...,https://www.zefix.admin.ch/it/search/entity/li...,https://www.zefix.admin.ch/en/search/entity/li...
2,A1 engineering ag,1055874,CHE212607256,CH10037944356,1084,Eich,100,ACTIVE,2022-11-01,None,...,Neumattstrasse,2,,,Eich,6205,https://www.zefix.admin.ch/de/search/entity/li...,https://www.zefix.admin.ch/fr/search/entity/li...,https://www.zefix.admin.ch/it/search/entity/li...,https://www.zefix.admin.ch/en/search/entity/li...
3,A1 Immobilien & Consulting GmbH,1286247,CHE291691203,CH10048029571,1098,Ruswil,100,ACTIVE,2022-07-13,None,...,Grindel,34,,,Ruswil,6017,https://www.zefix.admin.ch/de/search/entity/li...,https://www.zefix.admin.ch/fr/search/entity/li...,https://www.zefix.admin.ch/it/search/entity/li...,https://www.zefix.admin.ch/en/search/entity/li...
4,A1-Service & Wellness Markus Bünder,1522916,CHE256528001,CH10018136673,1098,Ruswil,100,ACTIVE,2022-02-09,None,...,Schwerzistrasse,13,,,Ruswil,6017,https://www.zefix.admin.ch/de/search/entity/li...,https://www.zefix.admin.ch/fr/search/entity/li...,https://www.zefix.admin.ch/it/search/entity/li...,https://www.zefix.admin.ch/en/search/entity/li...
5,A1 Steuerberatung GmbH,1520104,CHE144486401,CH10048135462,1098,Ruswil,100,ACTIVE,2022-01-20,None,...,Grindel,34,,,Ruswil,6017,https://www.zefix.admin.ch/de/search/entity/li...,https://www.zefix.admin.ch/fr/search/entity/li...,https://www.zefix.admin.ch/it/search/entity/li...,https://www.zefix.admin.ch/en/search/entity/li...
6,A1 Treuhand GmbH,1167251,CHE379851330,CH10047974926,1098,Ruswil,100,ACTIVE,2026-03-13,None,...,Grindel,34,,,Ruswil,6017,https://www.zefix.admin.ch/de/search/entity/li...,https://www.zefix.admin.ch/fr/search/entity/li...,https://www.zefix.admin.ch/it/search/entity/li...,https://www.zefix.admin.ch/en/search/entity/li...
7,A1 Vorsorge-/ Vermögensberatung GmbH,1536235,CHE334250418,CH10048142412,1098,Ruswil,100,ACTIVE,2022-05-12,None,...,Grindel,34,,,Ruswil,6017,https://www.zefix.admin.ch/de/search/entity/li...,https://www.zefix.admin.ch/fr/search/entity/li...,https://www.zefix.admin.ch/it/search/entity/li...,https://www.zefix.admin.ch/en/search/entity/li...
8,A20-Immobilien AG,973574,CHE115464225,CH14030035675,1059,Kriens,100,ACTIVE,2023-05-31,None,...,Steinhofrain,17,,,Luzern,6005,https://www.zefix.admin.ch/de/search/entity/li...,https://www.zefix.admin.ch/fr/search/entity/li...,https://www.zefix.admin.ch/it/search/entity/li...,https://www.zefix.admin.ch/en/search/entity/li...
9,A2 Elektrobau Partner GmbH,1557345,CHE134913146,CH10048151672,1061,Luzern,100,ACTIVE,2022-10-20,None,...,Grossmatte,2b,,,Luzern,6014,https://www.zefix.admin.ch/de/search/entity/li...,https://www.zefix.admin.ch/fr/search/entity/li...,https://www.zefix.admin.ch/it/search/entity/li...,https://www.zefix.admin.ch/en/search/entity/li...

In [45]:
df_merged.to_csv("260517_full_zefix_export.csv", index=False, encoding="utf-8-sig")

In [46]:
import re
import time
import requests
from bs4 import BeautifulSoup
from datetime import datetime, date
from urllib.parse import urlparse

HEADERS_HRK = {
    "User-Agent": (
        "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 "
        "(KHTML, like Gecko) Chrome/120.0 Safari/537.36"
    ),
    "Accept-Language": "de-CH,de;q=0.9",
}

def _parse_eintragsdatum(response_text: str) -> date | None:
    m = re.search(
        r"Eingetragen am</span>\s*<span>(\d{2}\.\d{2}\.\d{4})</span>",
        response_text,
    )
    if not m:
        soup = BeautifulSoup(response_text, "html.parser")
        text = soup.get_text(" ", strip=True)
        m = re.search(
            r"Eingetragen\s+am[\s:]*?(\d{2}\.\d{2}\.\d{4})",
            text,
            flags=re.IGNORECASE,
        )
        if not m:
            return None
    return datetime.strptime(m.group(1), "%d.%m.%Y").date()

def scrape_eintragsdatum_from_url(
    url: str,
    session: requests.Session | None = None,
    timeout: int = 30,
) -> date | None:
    if not isinstance(url, str) or not url:
        return None
    
    sess = session or requests.Session()
    
    # 1) Seite laden → ViewState einsammeln
    r1 = sess.get(url, headers=HEADERS_HRK, timeout=timeout)
    r1.raise_for_status()
    soup = BeautifulSoup(r1.text, "html.parser")
    vs_el = soup.find("input", {"name": "javax.faces.ViewState"})
    if not vs_el:
        return None
    view_state = vs_el.get("value")
    
    # Origin aus der URL ableiten (für den Referer/Origin-Header)
    parsed = urlparse(url)
    origin = f"{parsed.scheme}://{parsed.hostname}"
    
    # 2) AJAX-Postback fürs Lazy-Panel
    ajax_headers = {
        **HEADERS_HRK,
        "Faces-Request": "partial/ajax",
        "X-Requested-With": "XMLHttpRequest",
        "Content-Type": "application/x-www-form-urlencoded; charset=UTF-8",
        "Origin": origin,
        "Referer": r1.url,
    }
    data = {
        "javax.faces.partial.ajax": "true",
        "javax.faces.source": "idAuszugForm:auszugContentPanel",
        "javax.faces.partial.execute": "idAuszugForm:auszugContentPanel",
        "javax.faces.partial.render": "idAuszugForm:auszugContentPanel",
        "idAuszugForm:auszugContentPanel_load": "true",
        "idAuszugForm": "idAuszugForm",
        "javax.faces.ViewState": view_state,
    }
    r2 = sess.post(url, data=data, headers=ajax_headers, timeout=timeout)
    r2.raise_for_status()
    
    return _parse_eintragsdatum(r2.text)

In [47]:
from tqdm import tqdm

tqdm.pandas()
sess = requests.Session()

def safe_scrape(url):
    try:
        result = scrape_eintragsdatum_from_url(url, session=sess)
        time.sleep(0.2)
        return result
    except Exception as e:
        print(f"Fehler bei {url}: {e}")
        return None

df_merged["eintragsdatum"] = df_merged["cantonalExcerptWeb"].progress_apply(safe_scrape)

/Users/gabriel/.pyenv/versions/3.11.1/lib/python3.11/html/parser.py:170: XMLParsedAsHTMLWarning: It looks like you're parsing an XML document using an HTML parser. If this really is an HTML document (maybe it's XHTML?), you can ignore or filter this warning. If it's XML, you should know that using an XML parser will be more reliable. To parse this document as XML, make sure you have the lxml package installed, and pass the keyword argument `features="xml"` into the BeautifulSoup constructor.
  k = self.parse_starttag(i)
 21%|███████▏                          | 7518/35340 [1:18:52<4:36:09,  1.68it/s]

Fehler bei https://lu.chregister.ch/cr-portal/auszug/auszug.xhtml?uid=CHE-486.134.292: 403 Client Error: Forbidden for url: https://lu.chregister.ch/cr-portal/auszug/auszug.xhtml?uid=CHE-486.134.292

 64%|█████████████████████            | 22578/35340 [3:57:14<2:04:40,  1.71it/s]

Fehler bei https://lu.chregister.ch/cr-portal/auszug/auszug.xhtml?uid=CHE-231.270.602: 403 Client Error: Forbidden for url: https://lu.chregister.ch/cr-portal/auszug/auszug.xhtml?uid=CHE-231.270.602

 69%|██████████████████████          | 24432/35340 [4:17:24<29:03:42,  9.59s/it]

Fehler bei https://lu.chregister.ch/cr-portal/auszug/auszug.xhtml?uid=CHE-254.953.534: HTTPSConnectionPool(host='lu.chregister.ch', port=443): Read timed out. (read timeout=30)

 76%|████████████████████████▍       | 26957/35340 [4:49:33<22:21:15,  9.60s/it]

Fehler bei https://lu.chregister.ch/cr-portal/auszug/auszug.xhtml?uid=CHE-345.912.519: HTTPSConnectionPool(host='lu.chregister.ch', port=443): Read timed out. (read timeout=30)

100%|███████████████████████████████████| 35340/35340 [6:22:59<00:00,  1.54it/s]

In [49]:
df_merged

,name_search,ehraid_search,uid,chid_search,legalSeatId_search,legalSeat_search,registryOfCommerceId_search,status_search,sogcDate_search,deletionDate_search,...,address.houseNumber,address.addon,address.poBox,address.city,address.swissZipCode,zefixDetailWeb.de,zefixDetailWeb.fr,zefixDetailWeb.it,zefixDetailWeb.en,eintragsdatum
0,A1 AUTO AG in Liquidation,437580,CHE107251578,CH10030216915,1094,Nottwil,100,BEING_CANCELLED,2026-03-24,None,...,20,,,Nottwil,6207,https://www.zefix.admin.ch/de/search/entity/li...,https://www.zefix.admin.ch/fr/search/entity/li...,https://www.zefix.admin.ch/it/search/entity/li...,https://www.zefix.admin.ch/en/search/entity/li...,1998-09-07
1,A1 Automobile GmbH,1434117,CHE338108860,CH10048096209,1093,Neuenkirch,100,ACTIVE,2020-04-27,None,...,14,,,Neuenkirch,6206,https://www.zefix.admin.ch/de/search/entity/li...,https://www.zefix.admin.ch/fr/search/entity/li...,https://www.zefix.admin.ch/it/search/entity/li...,https://www.zefix.admin.ch/en/search/entity/li...,2020-04-22
2,A1 engineering ag,1055874,CHE212607256,CH10037944356,1084,Eich,100,ACTIVE,2022-11-01,None,...,2,,,Eich,6205,https://www.zefix.admin.ch/de/search/entity/li...,https://www.zefix.admin.ch/fr/search/entity/li...,https://www.zefix.admin.ch/it/search/entity/li...,https://www.zefix.admin.ch/en/search/entity/li...,2012-04-11
3,A1 Immobilien & Consulting GmbH,1286247,CHE291691203,CH10048029571,1098,Ruswil,100,ACTIVE,2022-07-13,None,...,34,,,Ruswil,6017,https://www.zefix.admin.ch/de/search/entity/li...,https://www.zefix.admin.ch/fr/search/entity/li...,https://www.zefix.admin.ch/it/search/entity/li...,https://www.zefix.admin.ch/en/search/entity/li...,2016-12-06
4,A1-Service & Wellness Markus Bünder,1522916,CHE256528001,CH10018136673,1098,Ruswil,100,ACTIVE,2022-02-09,None,...,13,,,Ruswil,6017,https://www.zefix.admin.ch/de/search/entity/li...,https://www.zefix.admin.ch/fr/search/entity/li...,https://www.zefix.admin.ch/it/search/entity/li...,https://www.zefix.admin.ch/en/search/entity/li...,2022-02-04
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35335,8tungnaomi GmbH in Liquidation,1484627,CHE475219866,CH02040738992,1086,Grosswangen,100,BEING_CANCELLED,2025-05-30,None,...,1,,,Grosswangen,6022,https://www.zefix.admin.ch/de/search/entity/li...,https://www.zefix.admin.ch/fr/search/entity/li...,https://www.zefix.admin.ch/it/search/entity/li...,https://www.zefix.admin.ch/en/search/entity/li...,2021-04-26
35336,95' - Holding AG,1555017,CHE203663296,CH40034517342,1103,Sursee,100,ACTIVE,2025-03-05,None,...,24,,,Sursee,6210,https://www.zefix.admin.ch/de/search/entity/li...,https://www.zefix.admin.ch/fr/search/entity/li...,https://www.zefix.admin.ch/it/search/entity/li...,https://www.zefix.admin.ch/en/search/entity/li...,2022-09-28
35337,969.coffee AG,1308378,CHE313609927,CH10038039590,1024,Emmen,100,ACTIVE,2026-01-15,None,...,5,,,Emmenbrücke,6020,https://www.zefix.admin.ch/de/search/entity/li...,https://www.zefix.admin.ch/fr/search/entity/li...,https://www.zefix.admin.ch/it/search/entity/li...,https://www.zefix.admin.ch/en/search/entity/li...,2017-06-08
35338,9.81 Arbeitssicherheit AG,1004437,CHE380242043,CH10037922823,1024,Emmen,100,ACTIVE,2026-02-06,None,...,10,,,Emmenbrücke,6020,https://www.zefix.admin.ch/de/search/entity/li...,https://www.zefix.admin.ch/fr/search/entity/li...,https://www.zefix.admin.ch/it/search/entity/li...,https://www.zefix.admin.ch/en/search/entity/li...,2010-12-23
35339,9K Consulting GmbH,1359322,CHE137269301,CH10048062369,1086,Grosswangen,100,ACTIVE,2018-09-06,None,...,65,,,Grosswangen,6022,https://www.zefix.admin.ch/de/search/entity/li...,https://www.zefix.admin.ch/fr/search/entity/li...,https://www.zefix.admin.ch/it/search/entity/li...,https://www.zefix.admin.ch/en/search/entity/li...,2018-08-06

In [48]:
df_merged.to_csv("260517_full_zefix_export_eintragsdatum.csv", index=False, encoding="utf-8-sig")